### ISSUE TITLE
Trying to add a youtube link using the addon shows an error message

### ISSUE THREAD

**Issue by e-alfred** [e-alfred/ocDownloader_webextension#1]
Trying to add a Youtube URL to ocDownloader using the addon by right clicking on a video url and clicking "Add to OcDownloader" gives the following error message:

`Unable to retrieve true Youtube Video URL`

**Comment by soloam** [comment]
I'm having the same problem in nextcloud, but if I run youtube-dl in the command line it works and returns the movie. Any news on this?

Thank you

**Comment by e-alfred** [comment]
Yes, it is not an extension problem. The youtube-dl path is not set in api.php, therefore no real download links are generated. Please see this issue: https://github.com/e-alfred/ocdownloader/issues/37

**Comment by e-alfred** [comment]
Finally fixed by https://github.com/e-alfred/ocdownloader/commit/019888a4943c1be14fac1aac0345ac4d32823ce7.
