### ISSUE TITLE
Firefox extension only installable temporarily in debug mode

### ISSUE THREAD

**Issue by Ra72xx** [e-alfred/ocDownloader_webextension#2]
The web extension fails to install with current Firefox versions, as FF considers the extension as corrupt. It only works when enabling debug mode and using the option to temporarily install an extension. Which means it is gone the next time using FF.

Makes the extension unusable for daily use unfortunately :-(

**Comment by e-alfred** [comment]
The app has to be signed to make the installation in Firefox work (except you disable addon signing in about:config). I will upload it to AMO, in the meantime the old extension from the original developer will work until Firefox 57.

**Comment by Ra72xx** [comment]
Do you mean xpinstall.signatures.enabled? This doesn't change anything for me.

**Comment by e-alfred** [comment]
The new extension is available here, it is compatible with Firefox 57+ too:

https://addons.mozilla.org/addon/ocdownloader-firefox/

Disabling signatures won't help in newer Firefox versions, it has to be signed (except in debug mode).

**Comment by Ra72xx** [comment]
Thanks!
