### ISSUE TITLE
Configure the extension

### ISSUE THREAD

**Issue by Naimadnap** [e-alfred/ocDownloader_webextension#7]
I have nextcloud instance in my RPi home server behind ddns service but visible from the web. The extension can not login to the server. I get error No response from ocDownloader on your server.

ocDownloader plugin insatalled via store
aria installed as is in Readme

from NC logs
--
Error: Call to undefined method Exception::getResult() at /var/www/nextcloud/ocs/v1.php#71

**Comment by e-alfred** [comment]
This is fixed now by https://github.com/e-alfred/ocdownloader/commit/49dd4afd13f3a58fd591e789d407d10ad09dfa6c.

You have to update both the extensions as well as ocDownloader.

**Comment by Naimadnap** [comment]
Hi @e-alfred,

thanks for fix but still the chrome extension can not connect with my nextcloud instance.
NextCloud version: 15.0.6
ocDownloader extension: 1.6.1
Chrome version: 73.0.3683.103 (64-bitowa) for MAC
ocDownloader app for NextCloud: 1.6.3

error on notification from browser: No response from ocDownloader on your server.
Any entry in NC logs (viewed by GUI)

apahe log
`[29/Apr/2019:08:42:01 +0100] "POST /index.php/apps/ocdownloader/api/version?format=json HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36 Vivaldi/2.4.1488.35"`

**Comment by e-alfred** [comment]
You also need a new version of ocDownloader to get a working API. I uploaded a new release to the App Store (version 1.7.0), please test it out to see if it works.

**Comment by Naimadnap** [comment]
In chrome web store is still 1.6.1, I will wait a while and try again

**Comment by e-alfred** [comment]
The extension is okay, I meant the ocDownloader app for Nextcloud.

**Comment by Naimadnap** [comment]
so after update to 1.7.0

`Accessing static property OCA\ocDownloader\Controller\Lib\API::$YTDLBinary as non static at /var/www/nextcloud/apps/ocdownloader/controller/lib/api.php#56`

should I move this issue to https://github.com/e-alfred/ocdownloader ?

**Comment by e-alfred** [comment]
This is a known warning that should be fixed in the future but it shouldn't cause a problem with the extensions.

I made several changes to the extensions, can you download them from the Chrome Web Store or AMO and test them?

**Comment by Naimadnap** [comment]
it seems to works correctly
